/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_EventL1LoggedMDTConfig_H_
#define	_Ngap_EventL1LoggedMDTConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_MeasurementThresholdL1LoggedMDT.h"
#include "Ngap_Hysteresis.h"
#include "Ngap_TimeToTrigger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_ProtocolExtensionContainer;

/* Ngap_EventL1LoggedMDTConfig */
typedef struct Ngap_EventL1LoggedMDTConfig {
	Ngap_MeasurementThresholdL1LoggedMDT_t	 l1Threshold;
	Ngap_Hysteresis_t	 hysteresis;
	Ngap_TimeToTrigger_t	 timeToTrigger;
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_EventL1LoggedMDTConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_EventL1LoggedMDTConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_EventL1LoggedMDTConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_EventL1LoggedMDTConfig_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_EventL1LoggedMDTConfig_H_ */
#include <asn_internal.h>
