/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_ProcedureStageChoice_H_
#define	_Ngap_ProcedureStageChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_ProcedureStageChoice_PR {
	Ngap_ProcedureStageChoice_PR_NOTHING,	/* No components present */
	Ngap_ProcedureStageChoice_PR_first_dl_count,
	Ngap_ProcedureStageChoice_PR_choice_Extensions
} Ngap_ProcedureStageChoice_PR;

/* Forward declarations */
struct Ngap_FirstDLCount;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_ProcedureStageChoice */
typedef struct Ngap_ProcedureStageChoice {
	Ngap_ProcedureStageChoice_PR present;
	union Ngap_ProcedureStageChoice_u {
		struct Ngap_FirstDLCount	*first_dl_count;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProcedureStageChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProcedureStageChoice;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_ProcedureStageChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_ProcedureStageChoice_1[2];
extern asn_per_constraints_t asn_PER_type_Ngap_ProcedureStageChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_ProcedureStageChoice_H_ */
#include <asn_internal.h>
