/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_UE_DifferentiationInfo_H_
#define	_Ngap_UE_DifferentiationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_UE_DifferentiationInfo__periodicCommunicationIndicator {
	Ngap_UE_DifferentiationInfo__periodicCommunicationIndicator_periodically	= 0,
	Ngap_UE_DifferentiationInfo__periodicCommunicationIndicator_ondemand	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_UE_DifferentiationInfo__periodicCommunicationIndicator;
typedef enum Ngap_UE_DifferentiationInfo__stationaryIndication {
	Ngap_UE_DifferentiationInfo__stationaryIndication_stationary	= 0,
	Ngap_UE_DifferentiationInfo__stationaryIndication_mobile	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_UE_DifferentiationInfo__stationaryIndication;
typedef enum Ngap_UE_DifferentiationInfo__trafficProfile {
	Ngap_UE_DifferentiationInfo__trafficProfile_single_packet	= 0,
	Ngap_UE_DifferentiationInfo__trafficProfile_dual_packets	= 1,
	Ngap_UE_DifferentiationInfo__trafficProfile_multiple_packets	= 2
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_UE_DifferentiationInfo__trafficProfile;
typedef enum Ngap_UE_DifferentiationInfo__batteryIndication {
	Ngap_UE_DifferentiationInfo__batteryIndication_battery_powered	= 0,
	Ngap_UE_DifferentiationInfo__batteryIndication_battery_powered_not_rechargeable_or_replaceable	= 1,
	Ngap_UE_DifferentiationInfo__batteryIndication_not_battery_powered	= 2
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_UE_DifferentiationInfo__batteryIndication;

/* Forward declarations */
struct Ngap_ScheduledCommunicationTime;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_UE-DifferentiationInfo */
typedef struct Ngap_UE_DifferentiationInfo {
	long	*periodicCommunicationIndicator;	/* OPTIONAL */
	long	*periodicTime;	/* OPTIONAL */
	struct Ngap_ScheduledCommunicationTime	*scheduledCommunicationTime;	/* OPTIONAL */
	long	*stationaryIndication;	/* OPTIONAL */
	long	*trafficProfile;	/* OPTIONAL */
	long	*batteryIndication;	/* OPTIONAL */
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_UE_DifferentiationInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_periodicCommunicationIndicator_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_stationaryIndication_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_trafficProfile_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_batteryIndication_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_UE_DifferentiationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_UE_DifferentiationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_UE_DifferentiationInfo_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_UE_DifferentiationInfo_H_ */
#include <asn_internal.h>
