/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_M1ThresholdType_H_
#define	_Ngap_M1ThresholdType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_Threshold-RSRP.h"
#include "Ngap_Threshold-RSRQ.h"
#include "Ngap_Threshold-SINR.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_M1ThresholdType_PR {
	Ngap_M1ThresholdType_PR_NOTHING,	/* No components present */
	Ngap_M1ThresholdType_PR_threshold_RSRP,
	Ngap_M1ThresholdType_PR_threshold_RSRQ,
	Ngap_M1ThresholdType_PR_threshold_SINR,
	Ngap_M1ThresholdType_PR_choice_Extensions
} Ngap_M1ThresholdType_PR;

/* Forward declarations */
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_M1ThresholdType */
typedef struct Ngap_M1ThresholdType {
	Ngap_M1ThresholdType_PR present;
	union Ngap_M1ThresholdType_u {
		Ngap_Threshold_RSRP_t	 threshold_RSRP;
		Ngap_Threshold_RSRQ_t	 threshold_RSRQ;
		Ngap_Threshold_SINR_t	 threshold_SINR;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_M1ThresholdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_M1ThresholdType;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_M1ThresholdType_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_M1ThresholdType_1[4];
extern asn_per_constraints_t asn_PER_type_Ngap_M1ThresholdType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_M1ThresholdType_H_ */
#include <asn_internal.h>
