/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_SuspendIndicator_H_
#define	_Ngap_SuspendIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_SuspendIndicator {
	Ngap_SuspendIndicator_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_SuspendIndicator;

/* Ngap_SuspendIndicator */
typedef long	 Ngap_SuspendIndicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_SuspendIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_SuspendIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_SuspendIndicator_specs_1;
asn_struct_free_f SuspendIndicator_free;
asn_struct_print_f SuspendIndicator_print;
asn_constr_check_f SuspendIndicator_constraint;
ber_type_decoder_f SuspendIndicator_decode_ber;
der_type_encoder_f SuspendIndicator_encode_der;
xer_type_decoder_f SuspendIndicator_decode_xer;
xer_type_encoder_f SuspendIndicator_encode_xer;
oer_type_decoder_f SuspendIndicator_decode_oer;
oer_type_encoder_f SuspendIndicator_encode_oer;
per_type_decoder_f SuspendIndicator_decode_uper;
per_type_encoder_f SuspendIndicator_encode_uper;
per_type_decoder_f SuspendIndicator_decode_aper;
per_type_encoder_f SuspendIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_SuspendIndicator_H_ */
#include <asn_internal.h>
