/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_SensorNameConfig_H_
#define	_Ngap_SensorNameConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_SensorNameConfig_PR {
	Ngap_SensorNameConfig_PR_NOTHING,	/* No components present */
	Ngap_SensorNameConfig_PR_uncompensatedBarometricConfig,
	Ngap_SensorNameConfig_PR_ueSpeedConfig,
	Ngap_SensorNameConfig_PR_ueOrientationConfig,
	Ngap_SensorNameConfig_PR_choice_Extensions
} Ngap_SensorNameConfig_PR;
typedef enum Ngap_SensorNameConfig__uncompensatedBarometricConfig {
	Ngap_SensorNameConfig__uncompensatedBarometricConfig_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_SensorNameConfig__uncompensatedBarometricConfig;
typedef enum Ngap_SensorNameConfig__ueSpeedConfig {
	Ngap_SensorNameConfig__ueSpeedConfig_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_SensorNameConfig__ueSpeedConfig;
typedef enum Ngap_SensorNameConfig__ueOrientationConfig {
	Ngap_SensorNameConfig__ueOrientationConfig_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_SensorNameConfig__ueOrientationConfig;

/* Forward declarations */
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_SensorNameConfig */
typedef struct Ngap_SensorNameConfig {
	Ngap_SensorNameConfig_PR present;
	union Ngap_SensorNameConfig_u {
		long	 uncompensatedBarometricConfig;
		long	 ueSpeedConfig;
		long	 ueOrientationConfig;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_SensorNameConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_uncompensatedBarometricConfig_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_ueSpeedConfig_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_ueOrientationConfig_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_SensorNameConfig;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_SensorNameConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_SensorNameConfig_1[4];
extern asn_per_constraints_t asn_PER_type_Ngap_SensorNameConfig_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_SensorNameConfig_H_ */
#include <asn_internal.h>
