/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_InterSystemHandoverReportType_H_
#define	_Ngap_InterSystemHandoverReportType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_InterSystemHandoverReportType_PR {
	Ngap_InterSystemHandoverReportType_PR_NOTHING,	/* No components present */
	Ngap_InterSystemHandoverReportType_PR_tooearlyIntersystemHO,
	Ngap_InterSystemHandoverReportType_PR_intersystemUnnecessaryHO,
	Ngap_InterSystemHandoverReportType_PR_choice_Extensions
} Ngap_InterSystemHandoverReportType_PR;

/* Forward declarations */
struct Ngap_TooearlyIntersystemHO;
struct Ngap_IntersystemUnnecessaryHO;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_InterSystemHandoverReportType */
typedef struct Ngap_InterSystemHandoverReportType {
	Ngap_InterSystemHandoverReportType_PR present;
	union Ngap_InterSystemHandoverReportType_u {
		struct Ngap_TooearlyIntersystemHO	*tooearlyIntersystemHO;
		struct Ngap_IntersystemUnnecessaryHO	*intersystemUnnecessaryHO;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_InterSystemHandoverReportType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_InterSystemHandoverReportType;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_InterSystemHandoverReportType_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_InterSystemHandoverReportType_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_InterSystemHandoverReportType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_InterSystemHandoverReportType_H_ */
#include <asn_internal.h>
