/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_EndIndication_H_
#define	_Ngap_EndIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_EndIndication {
	Ngap_EndIndication_no_further_data	= 0,
	Ngap_EndIndication_further_data_exists	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_EndIndication;

/* Ngap_EndIndication */
typedef long	 Ngap_EndIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_EndIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_EndIndication;
extern const asn_INTEGER_specifics_t asn_SPC_EndIndication_specs_1;
asn_struct_free_f EndIndication_free;
asn_struct_print_f EndIndication_print;
asn_constr_check_f EndIndication_constraint;
ber_type_decoder_f EndIndication_decode_ber;
der_type_encoder_f EndIndication_encode_der;
xer_type_decoder_f EndIndication_decode_xer;
xer_type_encoder_f EndIndication_encode_xer;
oer_type_decoder_f EndIndication_decode_oer;
oer_type_encoder_f EndIndication_encode_oer;
per_type_decoder_f EndIndication_decode_uper;
per_type_encoder_f EndIndication_encode_uper;
per_type_decoder_f EndIndication_decode_aper;
per_type_encoder_f EndIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_EndIndication_H_ */
#include <asn_internal.h>
