/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_NPN_PagingAssistanceInformation_H_
#define	_Ngap_NPN_PagingAssistanceInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_NPN_PagingAssistanceInformation_PR {
	Ngap_NPN_PagingAssistanceInformation_PR_NOTHING,	/* No components present */
	Ngap_NPN_PagingAssistanceInformation_PR_pNI_NPN_PagingAssistance,
	Ngap_NPN_PagingAssistanceInformation_PR_choice_Extensions
} Ngap_NPN_PagingAssistanceInformation_PR;

/* Forward declarations */
struct Ngap_Allowed_PNI_NPN_List;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_NPN-PagingAssistanceInformation */
typedef struct Ngap_NPN_PagingAssistanceInformation {
	Ngap_NPN_PagingAssistanceInformation_PR present;
	union Ngap_NPN_PagingAssistanceInformation_u {
		struct Ngap_Allowed_PNI_NPN_List	*pNI_NPN_PagingAssistance;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_NPN_PagingAssistanceInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_NPN_PagingAssistanceInformation;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_NPN_PagingAssistanceInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_NPN_PagingAssistanceInformation_1[2];
extern asn_per_constraints_t asn_PER_type_Ngap_NPN_PagingAssistanceInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_NPN_PagingAssistanceInformation_H_ */
#include <asn_internal.h>
