/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_Paging_Time_Window_H_
#define	_Ngap_Paging_Time_Window_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_Paging_Time_Window {
	Ngap_Paging_Time_Window_s1	= 0,
	Ngap_Paging_Time_Window_s2	= 1,
	Ngap_Paging_Time_Window_s3	= 2,
	Ngap_Paging_Time_Window_s4	= 3,
	Ngap_Paging_Time_Window_s5	= 4,
	Ngap_Paging_Time_Window_s6	= 5,
	Ngap_Paging_Time_Window_s7	= 6,
	Ngap_Paging_Time_Window_s8	= 7,
	Ngap_Paging_Time_Window_s9	= 8,
	Ngap_Paging_Time_Window_s10	= 9,
	Ngap_Paging_Time_Window_s11	= 10,
	Ngap_Paging_Time_Window_s12	= 11,
	Ngap_Paging_Time_Window_s13	= 12,
	Ngap_Paging_Time_Window_s14	= 13,
	Ngap_Paging_Time_Window_s15	= 14,
	Ngap_Paging_Time_Window_s16	= 15
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_Paging_Time_Window;

/* Ngap_Paging-Time-Window */
typedef long	 Ngap_Paging_Time_Window_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_Paging_Time_Window_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_Paging_Time_Window;
extern const asn_INTEGER_specifics_t asn_SPC_Paging_Time_Window_specs_1;
asn_struct_free_f Paging_Time_Window_free;
asn_struct_print_f Paging_Time_Window_print;
asn_constr_check_f Paging_Time_Window_constraint;
ber_type_decoder_f Paging_Time_Window_decode_ber;
der_type_encoder_f Paging_Time_Window_encode_der;
xer_type_decoder_f Paging_Time_Window_decode_xer;
xer_type_encoder_f Paging_Time_Window_encode_xer;
oer_type_decoder_f Paging_Time_Window_decode_oer;
oer_type_encoder_f Paging_Time_Window_encode_oer;
per_type_decoder_f Paging_Time_Window_decode_uper;
per_type_encoder_f Paging_Time_Window_encode_uper;
per_type_decoder_f Paging_Time_Window_decode_aper;
per_type_encoder_f Paging_Time_Window_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_Paging_Time_Window_H_ */
#include <asn_internal.h>
