/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_Range_H_
#define	_Ngap_Range_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_Range {
	Ngap_Range_m50	= 0,
	Ngap_Range_m80	= 1,
	Ngap_Range_m180	= 2,
	Ngap_Range_m200	= 3,
	Ngap_Range_m350	= 4,
	Ngap_Range_m400	= 5,
	Ngap_Range_m500	= 6,
	Ngap_Range_m700	= 7,
	Ngap_Range_m1000	= 8
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_Range;

/* Ngap_Range */
typedef long	 Ngap_Range_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_Range_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_Range;
extern const asn_INTEGER_specifics_t asn_SPC_Range_specs_1;
asn_struct_free_f Range_free;
asn_struct_print_f Range_print;
asn_constr_check_f Range_constraint;
ber_type_decoder_f Range_decode_ber;
der_type_encoder_f Range_encode_der;
xer_type_decoder_f Range_decode_xer;
xer_type_encoder_f Range_encode_xer;
oer_type_decoder_f Range_decode_oer;
oer_type_encoder_f Range_encode_oer;
per_type_decoder_f Range_decode_uper;
per_type_encoder_f Range_encode_uper;
per_type_decoder_f Range_decode_aper;
per_type_encoder_f Range_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_Range_H_ */
#include <asn_internal.h>
