/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_SONInformationReport_H_
#define	_Ngap_SONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_SONInformationReport_PR {
	Ngap_SONInformationReport_PR_NOTHING,	/* No components present */
	Ngap_SONInformationReport_PR_failureIndicationInformation,
	Ngap_SONInformationReport_PR_hOReportInformation,
	Ngap_SONInformationReport_PR_choice_Extensions
} Ngap_SONInformationReport_PR;

/* Forward declarations */
struct Ngap_FailureIndication;
struct Ngap_HOReport;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_SONInformationReport */
typedef struct Ngap_SONInformationReport {
	Ngap_SONInformationReport_PR present;
	union Ngap_SONInformationReport_u {
		struct Ngap_FailureIndication	*failureIndicationInformation;
		struct Ngap_HOReport	*hOReportInformation;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_SONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_SONInformationReport;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_SONInformationReport_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_SONInformationReport_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_SONInformationReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_SONInformationReport_H_ */
#include <asn_internal.h>
