/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_NB_IoT_Paging_eDRXCycle_H_
#define	_Ngap_NB_IoT_Paging_eDRXCycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_NB_IoT_Paging_eDRXCycle {
	Ngap_NB_IoT_Paging_eDRXCycle_hf2	= 0,
	Ngap_NB_IoT_Paging_eDRXCycle_hf4	= 1,
	Ngap_NB_IoT_Paging_eDRXCycle_hf6	= 2,
	Ngap_NB_IoT_Paging_eDRXCycle_hf8	= 3,
	Ngap_NB_IoT_Paging_eDRXCycle_hf10	= 4,
	Ngap_NB_IoT_Paging_eDRXCycle_hf12	= 5,
	Ngap_NB_IoT_Paging_eDRXCycle_hf14	= 6,
	Ngap_NB_IoT_Paging_eDRXCycle_hf16	= 7,
	Ngap_NB_IoT_Paging_eDRXCycle_hf32	= 8,
	Ngap_NB_IoT_Paging_eDRXCycle_hf64	= 9,
	Ngap_NB_IoT_Paging_eDRXCycle_hf128	= 10,
	Ngap_NB_IoT_Paging_eDRXCycle_hf256	= 11,
	Ngap_NB_IoT_Paging_eDRXCycle_hf512	= 12,
	Ngap_NB_IoT_Paging_eDRXCycle_hf1024	= 13
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_NB_IoT_Paging_eDRXCycle;

/* Ngap_NB-IoT-Paging-eDRXCycle */
typedef long	 Ngap_NB_IoT_Paging_eDRXCycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_NB_IoT_Paging_eDRXCycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_NB_IoT_Paging_eDRXCycle;
extern const asn_INTEGER_specifics_t asn_SPC_NB_IoT_Paging_eDRXCycle_specs_1;
asn_struct_free_f NB_IoT_Paging_eDRXCycle_free;
asn_struct_print_f NB_IoT_Paging_eDRXCycle_print;
asn_constr_check_f NB_IoT_Paging_eDRXCycle_constraint;
ber_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_ber;
der_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_der;
xer_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_xer;
xer_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_xer;
oer_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_oer;
oer_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_oer;
per_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_uper;
per_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_uper;
per_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_aper;
per_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_NB_IoT_Paging_eDRXCycle_H_ */
#include <asn_internal.h>
