/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_RSN_H_
#define	_Ngap_RSN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_RSN {
	Ngap_RSN_v1	= 0,
	Ngap_RSN_v2	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_RSN;

/* Ngap_RSN */
typedef long	 Ngap_RSN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_RSN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_RSN;
extern const asn_INTEGER_specifics_t asn_SPC_RSN_specs_1;
asn_struct_free_f RSN_free;
asn_struct_print_f RSN_print;
asn_constr_check_f RSN_constraint;
ber_type_decoder_f RSN_decode_ber;
der_type_encoder_f RSN_encode_der;
xer_type_decoder_f RSN_decode_xer;
xer_type_encoder_f RSN_encode_xer;
oer_type_decoder_f RSN_decode_oer;
oer_type_encoder_f RSN_encode_oer;
per_type_decoder_f RSN_decode_uper;
per_type_encoder_f RSN_encode_uper;
per_type_decoder_f RSN_decode_aper;
per_type_encoder_f RSN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_RSN_H_ */
#include <asn_internal.h>
