/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_NotifySourceNGRANNode_H_
#define	_Ngap_NotifySourceNGRANNode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_NotifySourceNGRANNode {
	Ngap_NotifySourceNGRANNode_notifySource	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_NotifySourceNGRANNode;

/* Ngap_NotifySourceNGRANNode */
typedef long	 Ngap_NotifySourceNGRANNode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_NotifySourceNGRANNode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_NotifySourceNGRANNode;
extern const asn_INTEGER_specifics_t asn_SPC_NotifySourceNGRANNode_specs_1;
asn_struct_free_f NotifySourceNGRANNode_free;
asn_struct_print_f NotifySourceNGRANNode_print;
asn_constr_check_f NotifySourceNGRANNode_constraint;
ber_type_decoder_f NotifySourceNGRANNode_decode_ber;
der_type_encoder_f NotifySourceNGRANNode_encode_der;
xer_type_decoder_f NotifySourceNGRANNode_decode_xer;
xer_type_encoder_f NotifySourceNGRANNode_encode_xer;
oer_type_decoder_f NotifySourceNGRANNode_decode_oer;
oer_type_encoder_f NotifySourceNGRANNode_encode_oer;
per_type_decoder_f NotifySourceNGRANNode_decode_uper;
per_type_encoder_f NotifySourceNGRANNode_encode_uper;
per_type_decoder_f NotifySourceNGRANNode_decode_aper;
per_type_encoder_f NotifySourceNGRANNode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_NotifySourceNGRANNode_H_ */
#include <asn_internal.h>
