/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#include "Ngap_ImmediateMDTNr.h"

#include "Ngap_M1Configuration.h"
#include "Ngap_M4Configuration.h"
#include "Ngap_M5Configuration.h"
#include "Ngap_M6Configuration.h"
#include "Ngap_M7Configuration.h"
#include "Ngap_BluetoothMeasurementConfiguration.h"
#include "Ngap_WLANMeasurementConfiguration.h"
#include "Ngap_MDT-Location-Info.h"
#include "Ngap_SensorMeasurementConfiguration.h"
#include "Ngap_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_Ngap_ImmediateMDTNr_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ngap_ImmediateMDTNr, measurementsToActivate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_MeasurementsToActivate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measurementsToActivate"
		},
	{ ATF_POINTER, 10, offsetof(struct Ngap_ImmediateMDTNr, m1Configuration),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_M1Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m1Configuration"
		},
	{ ATF_POINTER, 9, offsetof(struct Ngap_ImmediateMDTNr, m4Configuration),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_M4Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m4Configuration"
		},
	{ ATF_POINTER, 8, offsetof(struct Ngap_ImmediateMDTNr, m5Configuration),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_M5Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m5Configuration"
		},
	{ ATF_POINTER, 7, offsetof(struct Ngap_ImmediateMDTNr, m6Configuration),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_M6Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m6Configuration"
		},
	{ ATF_POINTER, 6, offsetof(struct Ngap_ImmediateMDTNr, m7Configuration),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_M7Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"m7Configuration"
		},
	{ ATF_POINTER, 5, offsetof(struct Ngap_ImmediateMDTNr, bluetoothMeasurementConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_BluetoothMeasurementConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bluetoothMeasurementConfiguration"
		},
	{ ATF_POINTER, 4, offsetof(struct Ngap_ImmediateMDTNr, wLANMeasurementConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_WLANMeasurementConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wLANMeasurementConfiguration"
		},
	{ ATF_POINTER, 3, offsetof(struct Ngap_ImmediateMDTNr, mDT_Location_Info),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_MDT_Location_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mDT-Location-Info"
		},
	{ ATF_POINTER, 2, offsetof(struct Ngap_ImmediateMDTNr, sensorMeasurementConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_SensorMeasurementConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sensorMeasurementConfiguration"
		},
	{ ATF_POINTER, 1, offsetof(struct Ngap_ImmediateMDTNr, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_ProtocolExtensionContainer_175P102,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_Ngap_ImmediateMDTNr_oms_1[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
static const ber_tlv_tag_t asn_DEF_Ngap_ImmediateMDTNr_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ngap_ImmediateMDTNr_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measurementsToActivate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* m1Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* m4Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* m5Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* m6Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* m7Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* bluetoothMeasurementConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* wLANMeasurementConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* mDT-Location-Info */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* sensorMeasurementConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_Ngap_ImmediateMDTNr_specs_1 = {
	sizeof(struct Ngap_ImmediateMDTNr),
	offsetof(struct Ngap_ImmediateMDTNr, _asn_ctx),
	asn_MAP_Ngap_ImmediateMDTNr_tag2el_1,
	11,	/* Count of tags in the map */
	asn_MAP_Ngap_ImmediateMDTNr_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	11,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ImmediateMDTNr = {
	"ImmediateMDTNr",
	"ImmediateMDTNr",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ImmediateMDTNr_tags_1,
	sizeof(asn_DEF_Ngap_ImmediateMDTNr_tags_1)
		/sizeof(asn_DEF_Ngap_ImmediateMDTNr_tags_1[0]), /* 1 */
	asn_DEF_Ngap_ImmediateMDTNr_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ngap_ImmediateMDTNr_tags_1)
		/sizeof(asn_DEF_Ngap_ImmediateMDTNr_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_ImmediateMDTNr_1,
	11,	/* Elements count */
	&asn_SPC_Ngap_ImmediateMDTNr_specs_1	/* Additional specs */
};

