/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_LoggedMDTTrigger_H_
#define	_Ngap_LoggedMDTTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_LoggedMDTTrigger_PR {
	Ngap_LoggedMDTTrigger_PR_NOTHING,	/* No components present */
	Ngap_LoggedMDTTrigger_PR_periodical,
	Ngap_LoggedMDTTrigger_PR_eventTrigger,
	Ngap_LoggedMDTTrigger_PR_choice_Extensions
} Ngap_LoggedMDTTrigger_PR;

/* Forward declarations */
struct Ngap_EventTrigger;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_LoggedMDTTrigger */
typedef struct Ngap_LoggedMDTTrigger {
	Ngap_LoggedMDTTrigger_PR present;
	union Ngap_LoggedMDTTrigger_u {
		NULL_t	 periodical;
		struct Ngap_EventTrigger	*eventTrigger;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_LoggedMDTTrigger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_LoggedMDTTrigger;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_LoggedMDTTrigger_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_LoggedMDTTrigger_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_LoggedMDTTrigger_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_LoggedMDTTrigger_H_ */
#include <asn_internal.h>
