/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_TimeToTrigger_H_
#define	_Ngap_TimeToTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_TimeToTrigger {
	Ngap_TimeToTrigger_ms0	= 0,
	Ngap_TimeToTrigger_ms40	= 1,
	Ngap_TimeToTrigger_ms64	= 2,
	Ngap_TimeToTrigger_ms80	= 3,
	Ngap_TimeToTrigger_ms100	= 4,
	Ngap_TimeToTrigger_ms128	= 5,
	Ngap_TimeToTrigger_ms160	= 6,
	Ngap_TimeToTrigger_ms256	= 7,
	Ngap_TimeToTrigger_ms320	= 8,
	Ngap_TimeToTrigger_ms480	= 9,
	Ngap_TimeToTrigger_ms512	= 10,
	Ngap_TimeToTrigger_ms640	= 11,
	Ngap_TimeToTrigger_ms1024	= 12,
	Ngap_TimeToTrigger_ms1280	= 13,
	Ngap_TimeToTrigger_ms2560	= 14,
	Ngap_TimeToTrigger_ms5120	= 15
} e_Ngap_TimeToTrigger;

/* Ngap_TimeToTrigger */
typedef long	 Ngap_TimeToTrigger_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_TimeToTrigger_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_TimeToTrigger;
extern const asn_INTEGER_specifics_t asn_SPC_TimeToTrigger_specs_1;
asn_struct_free_f TimeToTrigger_free;
asn_struct_print_f TimeToTrigger_print;
asn_constr_check_f TimeToTrigger_constraint;
ber_type_decoder_f TimeToTrigger_decode_ber;
der_type_encoder_f TimeToTrigger_encode_der;
xer_type_decoder_f TimeToTrigger_decode_xer;
xer_type_encoder_f TimeToTrigger_encode_xer;
oer_type_decoder_f TimeToTrigger_decode_oer;
oer_type_encoder_f TimeToTrigger_encode_oer;
per_type_decoder_f TimeToTrigger_decode_uper;
per_type_encoder_f TimeToTrigger_encode_uper;
per_type_decoder_f TimeToTrigger_decode_aper;
per_type_encoder_f TimeToTrigger_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_TimeToTrigger_H_ */
#include <asn_internal.h>
