/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_WLANMeasurementConfiguration_H_
#define	_Ngap_WLANMeasurementConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_WLANMeasConfig.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_WLANMeasurementConfiguration__wlan_rssi {
	Ngap_WLANMeasurementConfiguration__wlan_rssi_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_WLANMeasurementConfiguration__wlan_rssi;
typedef enum Ngap_WLANMeasurementConfiguration__wlan_rtt {
	Ngap_WLANMeasurementConfiguration__wlan_rtt_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_WLANMeasurementConfiguration__wlan_rtt;

/* Forward declarations */
struct Ngap_WLANMeasConfigNameList;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_WLANMeasurementConfiguration */
typedef struct Ngap_WLANMeasurementConfiguration {
	Ngap_WLANMeasConfig_t	 wlanMeasConfig;
	struct Ngap_WLANMeasConfigNameList	*wlanMeasConfigNameList;	/* OPTIONAL */
	long	*wlan_rssi;	/* OPTIONAL */
	long	*wlan_rtt;	/* OPTIONAL */
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_WLANMeasurementConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_wlan_rssi_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_Ngap_wlan_rtt_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_WLANMeasurementConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_WLANMeasurementConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_WLANMeasurementConfiguration_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_WLANMeasurementConfiguration_H_ */
#include <asn_internal.h>
