/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "asn.1/Container Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#include "Ngap_ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using Ngap_AMFPagingTarget_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_AreaScopeOfMDT_NR_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_AreaScopeOfMDT_EUTRA_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_BroadcastCancelledAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_BroadcastCompletedAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_CandidateCell_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_Cause_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_CellIDListForRestart_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_CPTransportLayerInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_DRBStatusDL_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_DRBStatusUL_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_ProcedureStageChoice_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_ENB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_EventTrigger_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_MeasurementThresholdL1LoggedMDT_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_GlobalRANNodeID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_GNB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_IntersystemSONTransferType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_IntersystemSONInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_IntersystemSONInformationReport_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_InterSystemHandoverReportType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_LastVisitedCellInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_LoggedMDTTrigger_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_MDTModeNr_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_M1ThresholdType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_N3IWF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NgENB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NGRAN_CGI_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NPN_AccessInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NPN_MobilityInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NPN_PagingAssistanceInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_NPN_Support_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_OverloadResponse_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_PWSFailedCellIDList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_QosCharacteristics_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_ResetType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_SensorNameConfig_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_SONInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_SONInformationReport_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_TargetID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_TNGF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_TWIF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UEHistoryInformationFromTheUE_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UEIdentityIndexValue_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UE_NGAP_IDs_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UEPagingIdentity_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UERLFReportContainer_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UPTransportLayerInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UserLocationInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_UserLocationInformationW_AGF_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_W_AGF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Ngap_WarningAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_AMFPagingTarget_ExtIEs_1,
	3,	/* Elements count */
	&asn_SPC_Ngap_AMFPagingTarget_ExtIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P1_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_AreaScopeOfMDT_NR_ExtIEs_5,
	3,	/* Elements count */
	&asn_SPC_Ngap_AreaScopeOfMDT_NR_ExtIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_AreaScopeOfMDT_EUTRA_ExtIEs_9,
	3,	/* Elements count */
	&asn_SPC_Ngap_AreaScopeOfMDT_EUTRA_ExtIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P3_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_BroadcastCancelledAreaList_ExtIEs_13,
	3,	/* Elements count */
	&asn_SPC_Ngap_BroadcastCancelledAreaList_ExtIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_BroadcastCompletedAreaList_ExtIEs_17,
	3,	/* Elements count */
	&asn_SPC_Ngap_BroadcastCompletedAreaList_ExtIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P5_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_CandidateCell_ExtIEs_21,
	3,	/* Elements count */
	&asn_SPC_Ngap_CandidateCell_ExtIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P6_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_Cause_ExtIEs_25,
	3,	/* Elements count */
	&asn_SPC_Ngap_Cause_ExtIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P7_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_CellIDListForRestart_ExtIEs_29,
	3,	/* Elements count */
	&asn_SPC_Ngap_CellIDListForRestart_ExtIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P8_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_CPTransportLayerInformation_ExtIEs_33,
	3,	/* Elements count */
	&asn_SPC_Ngap_CPTransportLayerInformation_ExtIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P9_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_DRBStatusDL_ExtIEs_37,
	3,	/* Elements count */
	&asn_SPC_Ngap_DRBStatusDL_ExtIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P10_tags_11[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_DRBStatusUL_ExtIEs_41,
	3,	/* Elements count */
	&asn_SPC_Ngap_DRBStatusUL_ExtIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P11_tags_12[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_ProcedureStageChoice_ExtIEs_45,
	3,	/* Elements count */
	&asn_SPC_Ngap_ProcedureStageChoice_ExtIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P12_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_ENB_ID_ExtIEs_49,
	3,	/* Elements count */
	&asn_SPC_Ngap_ENB_ID_ExtIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P13_tags_14[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_EventTrigger_ExtIEs_53,
	3,	/* Elements count */
	&asn_SPC_Ngap_EventTrigger_ExtIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P14_tags_15[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_MeasurementThresholdL1LoggedMDT_ExtIEs_57,
	3,	/* Elements count */
	&asn_SPC_Ngap_MeasurementThresholdL1LoggedMDT_ExtIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P15_tags_16[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_GlobalRANNodeID_ExtIEs_61,
	3,	/* Elements count */
	&asn_SPC_Ngap_GlobalRANNodeID_ExtIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P16_tags_17[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_GNB_ID_ExtIEs_65,
	3,	/* Elements count */
	&asn_SPC_Ngap_GNB_ID_ExtIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P17_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_IntersystemSONTransferType_ExtIEs_69,
	3,	/* Elements count */
	&asn_SPC_Ngap_IntersystemSONTransferType_ExtIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P18_tags_19[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_IntersystemSONInformation_ExtIEs_73,
	3,	/* Elements count */
	&asn_SPC_Ngap_IntersystemSONInformation_ExtIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P19_tags_20[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_IntersystemSONInformationReport_ExtIEs_77,
	3,	/* Elements count */
	&asn_SPC_Ngap_IntersystemSONInformationReport_ExtIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P20_tags_21[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_InterSystemHandoverReportType_ExtIEs_81,
	3,	/* Elements count */
	&asn_SPC_Ngap_InterSystemHandoverReportType_ExtIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P21_tags_22[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_LastVisitedCellInformation_ExtIEs_85,
	3,	/* Elements count */
	&asn_SPC_Ngap_LastVisitedCellInformation_ExtIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P22_tags_23[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_LoggedMDTTrigger_ExtIEs_89,
	3,	/* Elements count */
	&asn_SPC_Ngap_LoggedMDTTrigger_ExtIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P23_tags_24[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_MDTModeNr_ExtIEs_93,
	3,	/* Elements count */
	&asn_SPC_Ngap_MDTModeNr_ExtIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P24_tags_25[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_M1ThresholdType_ExtIEs_97,
	3,	/* Elements count */
	&asn_SPC_Ngap_M1ThresholdType_ExtIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P25_tags_26[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_N3IWF_ID_ExtIEs_101,
	3,	/* Elements count */
	&asn_SPC_Ngap_N3IWF_ID_ExtIEs_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P26_tags_27[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NgENB_ID_ExtIEs_105,
	3,	/* Elements count */
	&asn_SPC_Ngap_NgENB_ID_ExtIEs_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P27_tags_28[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NGRAN_CGI_ExtIEs_109,
	3,	/* Elements count */
	&asn_SPC_Ngap_NGRAN_CGI_ExtIEs_specs_109	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P28_tags_29[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NPN_AccessInformation_ExtIEs_113,
	3,	/* Elements count */
	&asn_SPC_Ngap_NPN_AccessInformation_ExtIEs_specs_113	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P29_tags_30[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NPN_MobilityInformation_ExtIEs_117,
	3,	/* Elements count */
	&asn_SPC_Ngap_NPN_MobilityInformation_ExtIEs_specs_117	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P30_tags_31[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NPN_PagingAssistanceInformation_ExtIEs_121,
	3,	/* Elements count */
	&asn_SPC_Ngap_NPN_PagingAssistanceInformation_ExtIEs_specs_121	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P31_tags_32[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_NPN_Support_ExtIEs_125,
	3,	/* Elements count */
	&asn_SPC_Ngap_NPN_Support_ExtIEs_specs_125	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P32_tags_33[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_OverloadResponse_ExtIEs_129,
	3,	/* Elements count */
	&asn_SPC_Ngap_OverloadResponse_ExtIEs_specs_129	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P33_tags_34[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_PWSFailedCellIDList_ExtIEs_133,
	3,	/* Elements count */
	&asn_SPC_Ngap_PWSFailedCellIDList_ExtIEs_specs_133	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P34_tags_35[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_QosCharacteristics_ExtIEs_137,
	3,	/* Elements count */
	&asn_SPC_Ngap_QosCharacteristics_ExtIEs_specs_137	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P35_tags_36[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_ResetType_ExtIEs_141,
	3,	/* Elements count */
	&asn_SPC_Ngap_ResetType_ExtIEs_specs_141	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P36_tags_37[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_SensorNameConfig_ExtIEs_145,
	3,	/* Elements count */
	&asn_SPC_Ngap_SensorNameConfig_ExtIEs_specs_145	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P37_tags_38[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_SONInformation_ExtIEs_149,
	3,	/* Elements count */
	&asn_SPC_Ngap_SONInformation_ExtIEs_specs_149	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P38_tags_39[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_SONInformationReport_ExtIEs_153,
	3,	/* Elements count */
	&asn_SPC_Ngap_SONInformationReport_ExtIEs_specs_153	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P39_tags_40[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_TargetID_ExtIEs_157,
	3,	/* Elements count */
	&asn_SPC_Ngap_TargetID_ExtIEs_specs_157	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P40_tags_41[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_TNGF_ID_ExtIEs_161,
	3,	/* Elements count */
	&asn_SPC_Ngap_TNGF_ID_ExtIEs_specs_161	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P41_tags_42[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_TWIF_ID_ExtIEs_165,
	3,	/* Elements count */
	&asn_SPC_Ngap_TWIF_ID_ExtIEs_specs_165	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P42_tags_43[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UEHistoryInformationFromTheUE_ExtIEs_169,
	3,	/* Elements count */
	&asn_SPC_Ngap_UEHistoryInformationFromTheUE_ExtIEs_specs_169	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P43_tags_44[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UEIdentityIndexValue_ExtIEs_173,
	3,	/* Elements count */
	&asn_SPC_Ngap_UEIdentityIndexValue_ExtIEs_specs_173	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P44_tags_45[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UE_NGAP_IDs_ExtIEs_177,
	3,	/* Elements count */
	&asn_SPC_Ngap_UE_NGAP_IDs_ExtIEs_specs_177	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P45_tags_46[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UEPagingIdentity_ExtIEs_181,
	3,	/* Elements count */
	&asn_SPC_Ngap_UEPagingIdentity_ExtIEs_specs_181	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P46_tags_47[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UERLFReportContainer_ExtIEs_185,
	3,	/* Elements count */
	&asn_SPC_Ngap_UERLFReportContainer_ExtIEs_specs_185	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P47_tags_48[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UPTransportLayerInformation_ExtIEs_189,
	3,	/* Elements count */
	&asn_SPC_Ngap_UPTransportLayerInformation_ExtIEs_specs_189	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P48_tags_49[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UserLocationInformation_ExtIEs_193,
	3,	/* Elements count */
	&asn_SPC_Ngap_UserLocationInformation_ExtIEs_specs_193	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P49_tags_50[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_UserLocationInformationW_AGF_ExtIEs_197,
	3,	/* Elements count */
	&asn_SPC_Ngap_UserLocationInformationW_AGF_ExtIEs_specs_197	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P50_tags_51[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_W_AGF_ID_ExtIEs_201,
	3,	/* Elements count */
	&asn_SPC_Ngap_W_AGF_ID_ExtIEs_specs_201	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52,
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52[0]), /* 1 */
	asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52,	/* Same as above */
	sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52)
		/sizeof(asn_DEF_Ngap_ProtocolIE_SingleContainer_127P51_tags_52[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ngap_WarningAreaList_ExtIEs_205,
	3,	/* Elements count */
	&asn_SPC_Ngap_WarningAreaList_ExtIEs_specs_205	/* Additional specs */
};

