/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_LoggingDuration_H_
#define	_Ngap_LoggingDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_LoggingDuration {
	Ngap_LoggingDuration_m10	= 0,
	Ngap_LoggingDuration_m20	= 1,
	Ngap_LoggingDuration_m40	= 2,
	Ngap_LoggingDuration_m60	= 3,
	Ngap_LoggingDuration_m90	= 4,
	Ngap_LoggingDuration_m120	= 5
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_LoggingDuration;

/* Ngap_LoggingDuration */
typedef long	 Ngap_LoggingDuration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_LoggingDuration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_LoggingDuration;
extern const asn_INTEGER_specifics_t asn_SPC_LoggingDuration_specs_1;
asn_struct_free_f LoggingDuration_free;
asn_struct_print_f LoggingDuration_print;
asn_constr_check_f LoggingDuration_constraint;
ber_type_decoder_f LoggingDuration_decode_ber;
der_type_encoder_f LoggingDuration_encode_der;
xer_type_decoder_f LoggingDuration_decode_xer;
xer_type_encoder_f LoggingDuration_encode_xer;
oer_type_decoder_f LoggingDuration_decode_oer;
oer_type_encoder_f LoggingDuration_encode_oer;
per_type_decoder_f LoggingDuration_decode_uper;
per_type_encoder_f LoggingDuration_encode_uper;
per_type_decoder_f LoggingDuration_decode_aper;
per_type_encoder_f LoggingDuration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_LoggingDuration_H_ */
#include <asn_internal.h>
