/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_LoggedMDTNr_H_
#define	_Ngap_LoggedMDTNr_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_LoggingInterval.h"
#include "Ngap_LoggingDuration.h"
#include "Ngap_LoggedMDTTrigger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_BluetoothMeasurementConfiguration;
struct Ngap_WLANMeasurementConfiguration;
struct Ngap_SensorMeasurementConfiguration;
struct Ngap_AreaScopeOfNeighCellsList;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_LoggedMDTNr */
typedef struct Ngap_LoggedMDTNr {
	Ngap_LoggingInterval_t	 loggingInterval;
	Ngap_LoggingDuration_t	 loggingDuration;
	Ngap_LoggedMDTTrigger_t	 loggedMDTTrigger;
	struct Ngap_BluetoothMeasurementConfiguration	*bluetoothMeasurementConfiguration;	/* OPTIONAL */
	struct Ngap_WLANMeasurementConfiguration	*wLANMeasurementConfiguration;	/* OPTIONAL */
	struct Ngap_SensorMeasurementConfiguration	*sensorMeasurementConfiguration;	/* OPTIONAL */
	struct Ngap_AreaScopeOfNeighCellsList	*areaScopeOfNeighCellsList;	/* OPTIONAL */
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_LoggedMDTNr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_LoggedMDTNr;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_LoggedMDTNr_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_LoggedMDTNr_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_LoggedMDTNr_H_ */
#include <asn_internal.h>
