/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_Paging_eDRX_Cycle_H_
#define	_Ngap_Paging_eDRX_Cycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_Paging_eDRX_Cycle {
	Ngap_Paging_eDRX_Cycle_hfhalf	= 0,
	Ngap_Paging_eDRX_Cycle_hf1	= 1,
	Ngap_Paging_eDRX_Cycle_hf2	= 2,
	Ngap_Paging_eDRX_Cycle_hf4	= 3,
	Ngap_Paging_eDRX_Cycle_hf6	= 4,
	Ngap_Paging_eDRX_Cycle_hf8	= 5,
	Ngap_Paging_eDRX_Cycle_hf10	= 6,
	Ngap_Paging_eDRX_Cycle_hf12	= 7,
	Ngap_Paging_eDRX_Cycle_hf14	= 8,
	Ngap_Paging_eDRX_Cycle_hf16	= 9,
	Ngap_Paging_eDRX_Cycle_hf32	= 10,
	Ngap_Paging_eDRX_Cycle_hf64	= 11,
	Ngap_Paging_eDRX_Cycle_hf128	= 12,
	Ngap_Paging_eDRX_Cycle_hf256	= 13
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_Paging_eDRX_Cycle;

/* Ngap_Paging-eDRX-Cycle */
typedef long	 Ngap_Paging_eDRX_Cycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_Paging_eDRX_Cycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_Paging_eDRX_Cycle;
extern const asn_INTEGER_specifics_t asn_SPC_Paging_eDRX_Cycle_specs_1;
asn_struct_free_f Paging_eDRX_Cycle_free;
asn_struct_print_f Paging_eDRX_Cycle_print;
asn_constr_check_f Paging_eDRX_Cycle_constraint;
ber_type_decoder_f Paging_eDRX_Cycle_decode_ber;
der_type_encoder_f Paging_eDRX_Cycle_encode_der;
xer_type_decoder_f Paging_eDRX_Cycle_decode_xer;
xer_type_encoder_f Paging_eDRX_Cycle_encode_xer;
oer_type_decoder_f Paging_eDRX_Cycle_decode_oer;
oer_type_encoder_f Paging_eDRX_Cycle_encode_oer;
per_type_decoder_f Paging_eDRX_Cycle_decode_uper;
per_type_encoder_f Paging_eDRX_Cycle_encode_uper;
per_type_decoder_f Paging_eDRX_Cycle_decode_aper;
per_type_encoder_f Paging_eDRX_Cycle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_Paging_eDRX_Cycle_H_ */
#include <asn_internal.h>
